# Generated by Django 3.1.1 on 2020-09-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=20)),
                ('AGE', models.IntegerField()),
                ('ADDRESS', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('SALARY', models.DecimalField(decimal_places=2, default=None, max_digits=18, null=True)),
            ],
        ),
    ]
