# Generated by Django 3.1.1 on 2020-09-24 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customertrain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=100)),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=18)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customertrain.manufacturers')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Orders',
            fields=[
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
                ('fulfill_by_date', models.DateField(default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customertrain.clients')),
                ('products', models.ManyToManyField(to='customertrain.Products')),
            ],
        ),
    ]
