# Generated by Django 3.1.1 on 2020-09-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customertrain', '0002_client_orders_clients_manufacturers_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_orders',
            name='fulfill_by_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='SALARY',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True),
        ),
    ]
