# Generated by Django 3.1.1 on 2020-09-23 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.BigIntegerField(default=1000000, verbose_name='sum of all money in the bank')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('account_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('sum_balance', models.BigIntegerField(default=10000, verbose_name='sum of saving and checking balance')),
                ('type_selection', models.CharField(choices=[('C', 'Credit'), ('I', 'Investment')], max_length=1)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banktrain.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Saving_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=10000, verbose_name='balance for saving account')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banktrain.bank_account')),
            ],
        ),
        migrations.CreateModel(
            name='Checking_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, verbose_name='balance for checking account')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_transaction', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banktrain.bank_account')),
            ],
        ),
    ]
