# Generated by Django 3.1.1 on 2020-09-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banktrain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking_account',
            name='bank_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banktrain.bank_account'),
        ),
        migrations.AlterField(
            model_name='saving_account',
            name='bank_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banktrain.bank_account'),
        ),
    ]
