# Generated by Django 3.1.1 on 2020-09-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_renew_due_back', 'Can renew due back')]},
        ),
    ]
